### PR TITLE
Mark users as attending only once event has started

### PR DESCRIPTION
**Pull request by itsmesatwik**
[Issue](https://github.com/HackIllinois/api/issues/58)
Added a function for validating the start of an event `CanCheckInEvent(string eventName)` and used that as a precondition in `MarkUserAsAttendingEvent` for only marking attending if event has started.
screen shot 2018-09-26 at 10 09 38 pm

### CODE REVIEW

**Comment by itsmesatwik** [comment]
I understand that I'm getting some type incompatibility, still waiting on a response from @ASankaran for clarifying how we're using time, once I get that, fixes are easy.

**Comment by YashoSharma** [comment]
Give this a readable name

**Comment by PradyumnaShome** [comment]
FYI you can run `go test` locally.

**Comment by YashoSharma** [comment]
Branch is stale and not being updated. Reopen if progress is made on this.

**Pull request closed without merging**
