### PR TITLE
Add food wave util

### PR DESCRIPTION
**Pull request by Timothy-Gonzalez**

### CODE REVIEW

**Comment by Timothy-Gonzalez** [comment]
Blocked by #544

**Comment by Timothy-Gonzalez** [comment]
Need to use `GET` then `PUT` it seems.

**Comment by Timothy-Gonzalez** [comment]
This should be good! 

Note that to test this locally, you must first create a bunch of users, register them all, apply decisions to them all, finalize those decisions, rsvp them, and then create their profiles. It will be required to use the `HackIllinois-Impersonate` header, and you may get 500s do to not being able to add roles (since they are fake users), but it will keep working.

**Comment by Timothy-Gonzalez** [comment]
Worked on prod on `309/310` users, took `11m23.242s`. In theory, this means it will always work and is perfectly coded.

**Comment by Timothy-Gonzalez** [comment]
One more thing Jared forgot to mention:
The script needs to assign each user that is assigned to a food wave to a notification topic (e.g. "FoodWave1", "FoodWave2"). The topics FoodWave1 and FoodWave2 already on prod, so all that needs to be done is assigning each appropriate user.

**Comment by Timothy-Gonzalez** [comment]
Success on 727/727 users, only took 15:43.59. Going to add a little message and some quality things.

**Review by Nydauron — APPROVED** [review]

**Review by asehgal220 — APPROVED** [review]

**Pull request merged**
